---
title: World of Tanks | Мир боевых танков
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mikhailyand@ya.ru
description: Информационный портал игры World of Tanks. Актуальные новости WoT, инструкции
  и гайды для игроков, тактика игры, обзоры танков. Скачать моды для World of Tanks
  и подборки модов для игры...
baseurl: 
url: https://protanks.ru
permalink: "/:title"
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
twitter:
  card: summary_large_image
