---
title: Мир танков Lesta Games
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mikhailyand@ya.ru
description: Информационный портал игры "Мир танков" от Lesta Games: новости, гайды, тактические рекомендации и обзоры техники.
baseurl: 
url: https://playtanks.ru
permalink: "/:title"
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
twitter:
  card: summary_large_image
